version: 1.2
workflows:
   - name: mhubaiColabWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: colab_workflow.wdl
   - name: mhubaiDockerfileWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: dockerfile_workflow.wdl
