version: 1.2
workflows:
   - name: mhubaiColabWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /src/wdl/colab_workflow.wdl
   - name: mhubaiDockerfileWorkflowOnTerra
     subclass: WDL
     primaryDescriptorPath: /src/wdl/dockerfile_workflow.wdl
