version: 1.2
workflows:
   - name: mhubaiColabWorkflow
     subclass: WDL
     primaryDescriptorPath: /src/wdl/colab_workflow.wdl
   - name: mhubaiDockerfileWorkflow
     subclass: WDL
     primaryDescriptorPath: /src/wdl/dockerfile_workflow.wdl
